INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (1,101,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (1,102,77); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (1,103,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (2,101,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (2,103,47); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (2,104,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (3,102,29); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (3,103,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (3,104,49); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (4,101,79); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (4,102,30); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (4,104,90); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (5,101,93); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (5,102,89); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (5,103,68); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (6,103,73); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (6,104,30); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (6,105,74); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (7,101,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (7,103,91); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (7,105,43); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (8,102,73); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (8,103,70); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (8,105,84); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (9,101,60); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (9,103,22); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (9,104,26); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (10,101,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (10,102,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (10,103,33); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (11,101,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (11,103,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (11,104,68); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (12,102,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (12,103,94); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (12,104,58); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (13,101,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (13,103,95); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (13,105,74); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (14,102,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (14,103,56); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (14,105,83); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (15,101,65); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (15,102,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (15,104,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (16,101,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (16,102,84); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (16,103,94); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (17,101,37); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (17,102,92); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (17,104,16); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (18,101,52); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (18,103,16); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (18,105,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (19,102,31); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (19,103,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (19,104,61); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (20,102,41); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (20,103,21); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (20,105,49); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (21,101,11); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (21,102,67); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (21,103,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (22,103,52); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (22,104,44); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (22,105,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (23,101,42); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (23,103,86); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (23,104,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (24,101,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (24,102,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (24,103,65); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (25,101,60); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (25,102,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (25,103,63); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (26,102,57); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (26,103,43); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (26,105,58); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (27,101,13); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (27,103,31); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (27,104,57); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (28,101,11); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (28,102,89); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (28,104,87); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (29,103,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (29,104,94); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (29,105,42); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (30,101,22); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (30,102,7);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (30,103,19); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (31,101,58); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (31,102,8);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (31,104,44); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (32,103,32); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (32,104,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (32,105,79); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (33,101,77); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (33,103,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (33,104,11); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (34,101,43); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (34,102,86); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (34,103,7);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (35,102,23); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (35,103,12); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (35,104,78); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (36,102,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (36,103,35); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (36,105,93); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (37,101,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (37,103,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (37,105,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (38,101,53); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (38,102,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (38,103,39); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (39,101,97); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (39,102,4);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (39,104,90); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (40,103,16); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (40,104,40); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (40,105,92); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (41,101,53); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (41,103,25); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (41,104,28); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (42,101,78); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (42,102,77); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (42,103,28); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (43,102,78); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (43,103,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (43,104,82); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (44,102,91); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (44,103,87); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (44,105,28); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (45,101,83); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (45,103,88); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (45,105,57); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (46,101,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (46,102,5);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (46,103,95); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (47,101,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (47,102,84); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (47,104,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (48,103,44); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (48,104,98); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (48,105,24); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (49,101,7);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (49,103,79); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (49,104,61); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (50,101,38); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (50,102,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (50,103,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (51,102,91); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (51,103,85); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (51,104,34); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (52,102,58); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (52,103,93); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (52,105,90); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (53,101,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (53,103,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (53,105,63); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (54,101,30); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (54,102,99); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (54,103,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (55,101,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (55,102,55); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (55,104,65); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (56,103,9);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (56,104,6);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (56,105,31); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (57,101,20); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (57,103,21); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (57,104,89); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (58,101,39); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (58,102,90); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (58,103,49); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (59,102,35); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (59,103,1);  --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (59,104,97); --