INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (1,101,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (1,102,77); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (1,103,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (2,101,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (2,103,47); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (2,104,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (3,102,29); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (3,103,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (3,104,49); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (4,101,79); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (4,102,30); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (4,104,90); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (5,101,93); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (5,102,89); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (5,103,68); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (6,103,73); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (6,104,30); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (6,105,74); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (7,101,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (7,103,91); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (7,105,43); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (8,102,73); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (8,103,70); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (8,105,84); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (9,101,60); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (9,103,22); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (9,104,26); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (10,101,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (10,102,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (10,103,33); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (11,101,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (11,103,51); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (11,104,68); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (12,102,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (12,103,94); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (12,104,58); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (13,101,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (13,103,95); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (13,105,74); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (14,102,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (14,103,56); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (14,105,83); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (15,101,65); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (15,102,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (15,104,80); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (16,101,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (16,102,84); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (16,103,94); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (17,101,37); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (17,102,92); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (17,104,16); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (18,101,52); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (18,103,16); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (18,105,48); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (19,102,31); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (19,103,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (19,104,61); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (20,102,41); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (20,103,21); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (20,105,49); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (21,101,11); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (21,102,67); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (21,103,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (22,103,52); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (22,104,44); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (22,105,15); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (23,101,42); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (23,103,86); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (23,104,18); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (24,101,17); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (24,102,71); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (24,103,65); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (25,101,60); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (25,102,59); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (25,103,63); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (26,102,57); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (26,103,43); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (26,105,58); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (27,101,13); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (27,103,31); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (27,104,57); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (28,101,11); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (28,102,89); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (28,104,87); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (29,103,62); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (29,104,94); --
INSERT INTO `enrollees_has_subjects` (`enrollees_id`,`subjects_id`,`score`) VALUES (29,105,42); --